### PR TITLE
Only get sitekey if not set in component template

### PR DESCRIPTION
**Pull request by devotox**

### CODE REVIEW

**Comment by devotox** [comment]
when will you cut a new release?

**Comment by joshsearles** [comment]
Today when I am able to access a computer, thanks for your contribution!

- Josh

**Comment by devotox** [comment]
No thank you!! for fixing the issues with the ember-g-recaptcha 🙇 

What do you think of renaming the component filename from ember-google-recaptcha to just google-recaptcha?

**Comment by joshsearles** [comment]
release to 0.1.1

Also, I'll take that into consideration! I know it's a long name for a
component.

When I find some time I need to flesh out all the dummy app stuff as i did
add the execute function to handle the Google reCaptcha invisible usage.

Cheers!

- Josh

**Pull request merged**
